/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MixedJava */

#ifndef _Included_MixedJava
#define _Included_MixedJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MixedJava
 * Method:    create_global_ref
 * Signature: (LMixedJava;)V
 */
JNIEXPORT void JNICALL Java_MixedJava_create_1global_1ref
  (JNIEnv *, jclass, jobject);

/*
 * Class:     MixedJava
 * Method:    delete_global_ref
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MixedJava_delete_1global_1ref
  (JNIEnv *, jclass);

/*
 * Class:     MixedJava
 * Method:    access_global_ref
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MixedJava_access_1global_1ref
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
