/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MixedJava */

#ifndef _Included_MixedJava
#define _Included_MixedJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MixedJava
 * Method:    get_version
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MixedJava_get_1version
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
