/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MixedJava */

#ifndef _Included_MixedJava
#define _Included_MixedJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MixedJava
 * Method:    set_field_f1
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_MixedJava_set_1field_1f1
  (JNIEnv *, jobject, jint);

/*
 * Class:     MixedJava
 * Method:    get_field_f1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MixedJava_get_1field_1f1
  (JNIEnv *, jobject);

/*
 * Class:     MixedJava
 * Method:    get_field_f2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MixedJava_get_1field_1f2
  (JNIEnv *, jobject);

/*
 * Class:     MixedJava
 * Method:    get_static_field
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MixedJava_get_1static_1field
  (JNIEnv *, jclass);

/*
 * Class:     MixedJava
 * Method:    set_static_field
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_MixedJava_set_1static_1field
  (JNIEnv *, jclass, jint);

/*
 * Class:     MixedJava
 * Method:    get_static_field_access_subclass
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MixedJava_get_1static_1field_1access_1subclass
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
