/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Fauxware */

#ifndef _Included_Fauxware
#define _Included_Fauxware
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Fauxware
 * Method:    authenticate
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_Fauxware_authenticate
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
