/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MixedJava */

#ifndef _Included_MixedJava
#define _Included_MixedJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MixedJava
 * Method:    concat_string
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MixedJava_concat_1string
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     MixedJava
 * Method:    strlen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_MixedJava_strlen
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
