/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MixedJava */

#ifndef _Included_MixedJava
#define _Included_MixedJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MixedJava
 * Method:    alloc_object
 * Signature: ()LMixedJava;
 */
JNIEXPORT jobject JNICALL Java_MixedJava_alloc_1object
  (JNIEnv *, jclass);

/*
 * Class:     MixedJava
 * Method:    new_object
 * Signature: ()LMixedJava;
 */
JNIEXPORT jobject JNICALL Java_MixedJava_new_1object
  (JNIEnv *, jclass);

/*
 * Class:     MixedJava
 * Method:    new_subclass_object
 * Signature: ()LSubMixedJava;
 */
JNIEXPORT jobject JNICALL Java_MixedJava_new_1subclass_1object
  (JNIEnv *, jclass);

/*
 * Class:     MixedJava
 * Method:    isinstanceof
 * Signature: (LMixedJava;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_MixedJava_isinstanceof
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     MixedJava
 * Method:    issameobject
 * Signature: (LMixedJava;LMixedJava;)I
 */
JNIEXPORT jint JNICALL Java_MixedJava_issameobject
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
