/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MixedJava */

#ifndef _Included_MixedJava
#define _Included_MixedJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MixedJava
 * Method:    native_boolean
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_MixedJava_native_1boolean
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     MixedJava
 * Method:    native_byte
 * Signature: (B)B
 */
JNIEXPORT jbyte JNICALL Java_MixedJava_native_1byte
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     MixedJava
 * Method:    native_char
 * Signature: (C)C
 */
JNIEXPORT jchar JNICALL Java_MixedJava_native_1char
  (JNIEnv *, jclass, jchar);

/*
 * Class:     MixedJava
 * Method:    native_short
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_MixedJava_native_1short
  (JNIEnv *, jclass, jshort);

/*
 * Class:     MixedJava
 * Method:    native_int
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_MixedJava_native_1int
  (JNIEnv *, jclass, jint);

/*
 * Class:     MixedJava
 * Method:    native_long
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_MixedJava_native_1long
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
