/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MixedJava */

#ifndef _Included_MixedJava
#define _Included_MixedJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MixedJava
 * Method:    native_callback
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MixedJava_native_1callback
  (JNIEnv *, jobject);

/*
 * Class:     MixedJava
 * Method:    native_callback_2
 * Signature: (LMixedJava;LMixedJava;)V
 */
JNIEXPORT void JNICALL Java_MixedJava_native_1callback_12
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     MixedJava
 * Method:    native_callbackA
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MixedJava_native_1callbackA
  (JNIEnv *, jobject);

/*
 * Class:     MixedJava
 * Method:    native_non_virtual_callback
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MixedJava_native_1non_1virtual_1callback
  (JNIEnv *, jobject);

/*
 * Class:     MixedJava
 * Method:    native_static_callback
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MixedJava_native_1static_1callback
  (JNIEnv *, jclass);

/*
 * Class:     MixedJava
 * Method:    native_static_callback_2
 * Signature: ()LMixedJava;
 */
JNIEXPORT jobject JNICALL Java_MixedJava_native_1static_1callback_12
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
