/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MixedJava */

#ifndef _Included_MixedJava
#define _Included_MixedJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MixedJava
 * Method:    set_object_array_elem
 * Signature: ([LMixedJava;LMixedJava;I)V
 */
JNIEXPORT void JNICALL Java_MixedJava_set_1object_1array_1elem
  (JNIEnv *, jclass, jobjectArray, jobject, jint);

/*
 * Class:     MixedJava
 * Method:    get_object_array_elem
 * Signature: ([LMixedJava;I)LMixedJava;
 */
JNIEXPORT jobject JNICALL Java_MixedJava_get_1object_1array_1elem
  (JNIEnv *, jclass, jobjectArray, jint);

/*
 * Class:     MixedJava
 * Method:    create_new_object_array
 * Signature: (LMixedJava;)[LMixedJava;
 */
JNIEXPORT jobjectArray JNICALL Java_MixedJava_create_1new_1object_1array
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
